name: Sincronizza e Deploy su Render

on:
  schedule:
    - cron: '0 * * * *' # Controlla gli aggiornamenti ogni ora
  workflow_dispatch: # Ti permette di farlo partire anche a mano da GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il tuo codice
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Scarica tutta la cronologia, serve per il merge senza errori

      - name: Sincronizza con EasyProxy
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Collega il repository originale e scarica le novità
          git remote add upstream https://github.com/realbestia1/EasyProxy.git
          git fetch upstream
          
          # Si posiziona sulla branca principale corretta
          git checkout main || git checkout master
          
          # Unisce le novità nel tuo repository
          git merge upstream/main || git merge upstream/master --allow-unrelated-histories
          
          # Invia gli aggiornamenti sul tuo GitHub
          git push origin HEAD

      - name: Invia segnale di Deploy a Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d7solghkh4rs7398frug?key=bgntv1iuDuk"
